### PR TITLE
Switch to new recipe macro

### PR DESCRIPTION
**Pull request by tbreloff**
We could wait to merge until the new recipe macro hits Plots master?

### CODE REVIEW

**Comment by Evizero** [comment]
yes, well, with the new planned package I am not sure when the best time to merge is. maybe we should wait for the new package to be registered ?

**Comment by Evizero** [comment]
So I guess we agree that the smartest thing to do would be 

1.) what your are doing right now, i.e. changing all the code to the new RecipesBase. 
2.) register the RecipesBase
3.) move recipes to the actual packages we have control of.

So basically this package would become a catch-all package for plots of ML packages that don't want to have the definitions in their code

**Comment by tbreloff** [comment]
Hmm... I wanted to remove the Plots dependency from MLPlots, but corrplot doesn't use recipes... it makes plots calls directly.  I could rewrite it to use a recipe, or just add back the Plots dependency.  We could show off the no-Plots-dependency by adding the recipes to LearnBase instead.  We could still test the recipes in MLPlots.  What do you think?

**Comment by tbreloff** [comment]
Time to merge?  Moving recipes out of here and into LearnBase, OnlineAI, etc can happen in a new PR (or just a normal commit)

**Comment by Evizero** [comment]
sure go ahead. Concerning moving code to LearnBase. I would like to avoid magic dependencies (i.e. dependencies on untagged changes and/or packages that are not in METADATA) where I can, so I think we should wait until RecipeBase is registered. 

There is no need to remove Plots dependency from MLPlots IMHO, and yes, using it as a testing/maturing ground for new plots is a good idea

**Pull request merged**
